(function(){
function el(id){return document.getElementById(id);}
if(!document.getElementById("run-css")){
var st=document.createElement("style");st.id="run-css";
st.textContent=".head-actions{display:flex;flex-direction:column;align-items:flex-end;gap:8px}.head-btns{display:flex;gap:8px;align-items:center}.btn.run{min-height:42px;border-radius:999px;padding:8px 14px;background:linear-gradient(135deg,#63e2b3,#7ab8ff);border:0;color:#04140d;font:700 11px Comfortaa,sans-serif}.btn.run.live{animation:runpulse 1.4s ease-in-out infinite}@keyframes runpulse{50%{transform:scale(1.04)}}.livebar{display:none;gap:6px;flex-wrap:wrap;justify-content:flex-end;max-width:260px}.livebar.on{display:flex}.chip{padding:5px 8px;border-radius:999px;background:rgba(99,226,179,.12);border:1px solid rgba(99,226,179,.28);font:800 10px Comfortaa,sans-serif;color:#c8ffe8}.run-ov{position:fixed;inset:0;z-index:40;background:rgba(5,8,14,.86);display:none;padding:18px 14px;overflow:auto}.run-ov.on{display:block}.run-clock{font:800 64px Comfortaa,sans-serif;text-align:center;margin:8px 0;background:linear-gradient(90deg,#ff8bd4,#f0c27a,#63e2b3);-webkit-background-clip:text;background-clip:text;color:transparent}.modes{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin:12px 0}.modes button{border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.06);color:#fff;border-radius:999px;padding:10px 12px;font:700 12px Comfortaa,sans-serif}.modes button.on{color:#04140d;background:linear-gradient(135deg,#a8edea,#63e2b3)}.run-stats{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.run-stat{text-align:center;padding:14px 8px}.run-stat b{display:block;font:800 22px Comfortaa,sans-serif;color:#f0c27a}";
document.head.appendChild(st);}
var logout=el("logoutBtn");
if(logout&&!el("runOpenBtn")){
var wrap=document.createElement("div");wrap.className="head-actions";
wrap.innerHTML='<div class="head-btns"><button class="btn run" id="runOpenBtn" type="button">\u25b6 RUN</button></div><div class="livebar" id="livebar"><span class="chip" id="liveTime">00:00</span><span class="chip" id="liveKm">0.00 km</span><span class="chip" id="liveSpd">0.0</span><span class="chip" id="liveCal">0 kcal</span></div>';
logout.parentNode.insertBefore(wrap,logout);
wrap.querySelector(".head-btns").appendChild(logout);}
if(!el("homeRun")){var tm=el("homeTm");if(tm&&tm.parentNode&&tm.parentNode.parentNode){var row=document.createElement("div");row.className="kv";row.innerHTML="<span>run</span><b id=\"homeRun\">-</b>";tm.parentNode.parentNode.insertBefore(row,tm.parentNode.nextSibling);}}
if(!el("runOv")){var ov=document.createElement("div");ov.className="run-ov";ov.id="runOv";ov.innerHTML='<div class="wrap" style="padding-top:8px"><div class="row" style="justify-content:space-between"><p class="badge">LIVE RUN</p><button class="btn ghost" id="runCloseBtn" type="button">close</button></div><div class="run-clock" id="runClock">00:00</div><p class="sub" id="runStatus" style="text-align:center">Pick a speed, then start</p><div class="modes" id="runModes"><button type="button" data-mode="walk" data-spd="4.5" class="on">Walk 4.5</button><button type="button" data-mode="jog" data-spd="6.5">Jog 6.5</button><button type="button" data-mode="run" data-spd="8.5">Run 8.5</button><button type="button" data-mode="incline" data-spd="5.5">Incline 5.5</button><button type="button" data-mode="sprint" data-spd="11">Sprint 11</button></div><div class="grid"><div><label>speed km/h</label><input id="runSpeedIn" inputmode="decimal" value="4.5"></div><div><label>incline %</label><input id="runInclineIn" inputmode="decimal" value="0"></div></div><div class="run-stats"><div class="glass run-stat"><b id="ovKm">0.00</b><span>km</span></div><div class="glass run-stat"><b id="ovSpd">0.0</b><span>km/h</span></div><div class="glass run-stat"><b id="ovCal">0</b><span>kcal</span></div><div class="glass run-stat"><b id="ovPace">-</b><span>pace</span></div></div><div class="row" style="margin-top:8px"><button class="btn ok full" id="runStartBtn" type="button">start</button><button class="btn ghost full hidden" id="runPauseBtn" type="button">stop</button><button class="btn full hidden" id="runResumeBtn" type="button">resume</button><button class="btn danger full hidden" id="runEndBtn" type="button">end run</button></div></div>';document.body.appendChild(ov);}
})();
